kind: ConfigMap 
apiVersion: v1 
metadata:
  name: gateway-configmap 
data:
  DISCOVERY_LOCATOR_ENABLED: 'true'
  EUREKA_PREFEREDIP_ENABLED: 'false'
  EUREKA_URL: 'http://discovery:8761/eureka'
  GATEWAY_CONNECT_TIMEOUT: '3000'
  GATEWAY_PORT: '9999'
  GATEWAY_RESPONCE_TIMEOUT: '3000'
  SERVICE_NAME: 'gateway'
    
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway-app
  labels:
    app: gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-app
  template:
    metadata:
      labels:
        app: gateway-app
    spec:
      containers:
      - name: gateway-app
        image: registry.diasoft.ru:5000/gateway:1.1.0-SNAPSHOT
        env:
            - name: EUREKA_PREFEREDIP_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: EUREKA_PREFEREDIP_ENABLED
                  name: gateway-configmap
            - name: GATEWAY_PORT
              valueFrom:
                configMapKeyRef:
                  key: GATEWAY_PORT
                  name: gateway-configmap
            - name: GATEWAY_RESPONCE_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: GATEWAY_RESPONCE_TIMEOUT
                  name: gateway-configmap
            - name: DISCOVERY_LOCATOR_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: DISCOVERY_LOCATOR_ENABLED
                  name: gateway-configmap
            - name: EUREKA_URL
              valueFrom:
                configMapKeyRef:
                  key: EUREKA_URL
                  name: gateway-configmap
            - name: GATEWAY_CONNECT_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: GATEWAY_CONNECT_TIMEOUT
                  name: gateway-configmap
#        ports:
#        - containerPort: 7050
#        livenessProbe:
#          httpGet:
#            path: /ping
#            port: 7050
#          initialDelaySeconds: 20
#          periodSeconds: 10
#        readinessProbe:
#          httpGet:
#            path: /ping
#            port: 7050
#          initialDelaySeconds: 40
#          periodSeconds: 20
          
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-app
  labels:
    app: gateway-app
spec:
  type: NodePort
  selector:
    app: gateway-app
  ports:
  - port: 9999
    protocol: "TCP"
    name: "http"