server:
  port: 9999

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 30000
        response-timeout: 30000
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      default-filters: RuleListFilter

# !!! Set discovery:locator:enabled:false to enable routing only using rules described below. !!!
#      routes:
#      - id: template_route
#        uri: lb://template
#        predicates:
#        - Path=/template/**
#        filters:
#        - RewritePath=/template/(?<path>.*), /$\{path}

eureka:
  client:
    enabled: true
    register-with-eureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

gateway:
  params:
    rule-list-dir: ./
    rule-list-name: client-whitelist
    rule-list-cache-time-live-min: 0

