spring:
  kafka:
    consumer:
      bootstrap-servers: ${SPRING_KAFKA_CONSUMER_SERVER:localhost:9092}
      group-id: demo
    producer:
      bootstrap-servers: ${SPRING_KAFKA_PRODUCER_SERVER:localhost:9092}